xcopy W:\Documents\SourceCode\Windows\UtilORama4\LaunchORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\MapORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\MergeORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\SplitORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\ChannelORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\VampORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\CompareORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\TimeORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\InfoRama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\RGBORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\SparkleORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
xcopy W:\Documents\SourceCode\Windows\UtilORama4\DimORama\bin\Debug\*.* %1 /E/C/I/F/H/R/Y/Z
